config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#welcome'

  # for posts
  resources :posts do
    collection do
      get :upload_csv
      post :import_csv
      get :download
      get :search, to: "posts#search"
    end
    member do
      post :update_post
    end
  end

  # for users
  resources :users do
    collection do
      get :search, to: "users#search"
    end
    member do
    end
  end

  # for login
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#log_out'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  # for password reset
  get 'password/:id', to: 'passwords#edit', as: 'edit_password'
  post 'password/:id', to: 'passwords#update'

  get 'reset/password', to: 'passwords#new'
  post 'reset/password', to: 'passwords#create'
  get 'reset/password/edit', to: 'passwords#editReset'
  patch 'reset/password/edit', to: 'passwords#updateReset'

end

app/views/layouts/_alerts.html.slim
.alert.alert-dismissible.fade.show.bg-warning.blue role="alert"
  = notice
  button.close type="button" data-dismiss="alert" aria-label="Close"
    span aria-hidden="true" ="&times".html_safe

app/views/layouts/_footer.html.slim
footer 
  .footer.text-center.py-3.bg-primary
    a href="http://seattleconsultingmyanmar.com/en" class="text-light" Seattle Consulting Myanmar Co.,Ltd. All rights reserved. © Copyright

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-primary.text-light
  = link_to "Home", root_path , class:"navbar-brand text-light"
  h5.text-center Employee Management System
  .collapse.navbar-collapse id="navbarSupportedContent"
    -if logged_in?
      ul.navbar-nav.mr-auto
        
      ul.navbar-nav.my-sm-0
        -if admin?
          li.nav-item
            = link_to "Create New Employee", new_user_path , class:"nav-link text-light"
        li.nav-item 
          .dropdown.show
            a.nav-link.dropdown-toggle.text-light role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              = current_user.name
            .dropdown-menu aria-labelledby="dropdownMenuLink" style="left:-75px;"
              = link_to "Profile", user_path(current_user) , class:"dropdown-item"
              = link_to "Edit", edit_user_path(current_user), class: 'dropdown-item'
              = link_to "Change Password", edit_password_path(current_user), class: 'dropdown-item'
              = link_to "Log Out", logout_path , class:"dropdown-item"
          
          

app/views/layouts/application.html.slim
doctype html
html
  head
    title OJT
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    / / Bootstrap CSS & JS Library
    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"
    = stylesheet_link_tag  'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css'

    / / Datatable
    = stylesheet_link_tag  'https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css'
    = stylesheet_link_tag  'https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js'
    script src= "https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js" 

    / / Custom JS and CSS
    
    = stylesheet_link_tag  "common"

  body
    -if logged_in?
      = render 'layouts/header'  
    -if notice 
      = render 'layouts/alerts'  
    .wrapper
      = yield 
    -if logged_in? 
      = render 'layouts/footer'
javascript:
  $(document).ready( function () {
    $('#table_id').DataTable();
 });    
  
    

app/views/layouts/temp.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OJT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css' %>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
    
  <style>

  body{
    max-width: 1920px;
  }

  .wrapper{
    width: 90%;
    margin: 0 auto;
  }

  .form-wrapper{
    width: 50%;
    margin: 0 auto;
  }

  .alert{
    border-radius: 0;
  }

  h1{
    padding: 10px 0;
  }

  table{
    padding: 20px 0;
  }

  .error-msg{
    color: #c77700;
    margin: 5px 0;
  }

  .mv-20{
    margin: 20px 0;
  }

  .mb-20{
    margin: 0 0 20px 0;
  }

  .mr-5{
    margin-right: 5px;
  }

  .mv-r-20{
    margin: 20px 5px 20px 0;
  }

  .profile img{
    height: 120px;
    width:  auto;
  }

  .button1{
    background: #3d61d9;
    color: #fff;
  }

  .button2{
    background: #001a6e;
  }

  .button1:hover{
    opacity: .7;
    color: #fff;
  }

  .btn-wid{
    width: 50%;
  }

  .blue{
    background: #3d61d9;
    color: #fff;
  }

  .card{
    text-align: center;
    padding: 20px;
    width: 30%;
    margin: 150px auto;
    border-radius: 10px;
    box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
  }

  .not-card{
    text-align: center;
    width:100%;
    padding: 20px;
    margin: 300px auto;
  }

  .not-card1{
    margin: 30px 0 200px 0;
  }

  .not-card2{
    margin: 30px 0 250px 0;
    text-align: left;
  }

  .mb-350{
    margin: 30px auto 350px;
  }

  .mb-300{
    margin: 30px auto 300px;
  }

  footer{
    width: 100%;
    bottom: 0;
    position: fixed;
  }

  w-aut0{
    width: auto
  }
  </style>


  </head>

  <body>
  
  <% if logged_in? %>
    <%= render 'layouts/header' %>
  <% end %>
  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>
  <div class="wrapper">
  <%= yield %>
  </div>
  
  <% if logged_in? %>
  <%= render 'layouts/footer' %>
  <% end %>
  </body>
</html>

<script>
$(document).ready( function () {
    $('#table_id').DataTable();
} )

dataTable = $('#table_id').DataTable({
  "searching": false,
  "bLengthChange": false,
  "info": false,
})


</script>